### ISSUE TITLE
Dar daca se va introduce alt caracte, de ex virgula, punct etc?

### ISSUE THREAD

**Issue by asersun** [danielcode2020/tasksInternship#12]
https://github.com/danielcode2020/tasksInternship/blob/c064acf3dfef3c1078b6f5b21d73d14bf6dcdac1/Chapter16/Task16_14.java#L30

**Comment by danielcode2020** [comment]
Si pentru aceste caractere calcula number of occurences, dar deja am modificat sa calculeze doar pentru litere folosind intervalele din tabelul ASCII.
